// Code generated by go-swagger; DO NOT EDIT.

package default_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetInstructionsReader is a Reader for the GetInstructions structure.
type GetInstructionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInstructionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInstructionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInstructionsOK creates a GetInstructionsOK with default headers values
func NewGetInstructionsOK() *GetInstructionsOK {
	return &GetInstructionsOK{}
}

/*GetInstructionsOK handles this case with default header values.

Success
*/
type GetInstructionsOK struct {
}

func (o *GetInstructionsOK) Error() string {
	return fmt.Sprintf("[GET /instructions][%d] getInstructionsOK ", 200)
}

func (o *GetInstructionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
