// Code generated by go-swagger; DO NOT EDIT.

package default_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Logibox/civil-service-interview/v1/bpdts/models"
)

// GetUsersInCityReader is a Reader for the GetUsersInCity structure.
type GetUsersInCityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersInCityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUsersInCityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUsersInCityOK creates a GetUsersInCityOK with default headers values
func NewGetUsersInCityOK() *GetUsersInCityOK {
	return &GetUsersInCityOK{}
}

/*GetUsersInCityOK handles this case with default header values.

Success
*/
type GetUsersInCityOK struct {
	Payload models.UserList
}

func (o *GetUsersInCityOK) Error() string {
	return fmt.Sprintf("[GET /city/{city}/users][%d] getUsersInCityOK  %+v", 200, o.Payload)
}

func (o *GetUsersInCityOK) GetPayload() models.UserList {
	return o.Payload
}

func (o *GetUsersInCityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
