// Code generated by go-swagger; DO NOT EDIT.

package default_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUsersInCityParams creates a new GetUsersInCityParams object
// with the default values initialized.
func NewGetUsersInCityParams() *GetUsersInCityParams {
	var ()
	return &GetUsersInCityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersInCityParamsWithTimeout creates a new GetUsersInCityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUsersInCityParamsWithTimeout(timeout time.Duration) *GetUsersInCityParams {
	var ()
	return &GetUsersInCityParams{

		timeout: timeout,
	}
}

// NewGetUsersInCityParamsWithContext creates a new GetUsersInCityParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUsersInCityParamsWithContext(ctx context.Context) *GetUsersInCityParams {
	var ()
	return &GetUsersInCityParams{

		Context: ctx,
	}
}

// NewGetUsersInCityParamsWithHTTPClient creates a new GetUsersInCityParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUsersInCityParamsWithHTTPClient(client *http.Client) *GetUsersInCityParams {
	var ()
	return &GetUsersInCityParams{
		HTTPClient: client,
	}
}

/*GetUsersInCityParams contains all the parameters to send to the API endpoint
for the get users in city operation typically these are written to a http.Request
*/
type GetUsersInCityParams struct {

	/*City*/
	City string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get users in city params
func (o *GetUsersInCityParams) WithTimeout(timeout time.Duration) *GetUsersInCityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users in city params
func (o *GetUsersInCityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users in city params
func (o *GetUsersInCityParams) WithContext(ctx context.Context) *GetUsersInCityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users in city params
func (o *GetUsersInCityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users in city params
func (o *GetUsersInCityParams) WithHTTPClient(client *http.Client) *GetUsersInCityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users in city params
func (o *GetUsersInCityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCity adds the city to the get users in city params
func (o *GetUsersInCityParams) WithCity(city string) *GetUsersInCityParams {
	o.SetCity(city)
	return o
}

// SetCity adds the city to the get users in city params
func (o *GetUsersInCityParams) SetCity(city string) {
	o.City = city
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersInCityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param city
	if err := r.SetPathParam("city", o.City); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
