// Code generated by go-swagger; DO NOT EDIT.

// Package restapi interview api
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v1
//  Version: 0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
